

export const projets = [
    {
        _id: 0,
        title: "Reservia",
        tag: ["formation", "frontend",],
        desicription: "Transformez une maquette en site web avec HTML & CSS",
        imageURL: "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        objectif: [
            "Implémenter une interface responsive",
            "Intégrer du contenu conformément à une maquette",
        ],
        gitHub: "https://github.com/crist51/P2_degorre_christophe",
        site: "",
        article:"https://github.com/crist51/P2_degorre_christophe",
    },
    {
        _id: 1,
        title: "Homyfood",
        tag: ["formation", "frontend", "animation"],
        desicription: "Dynamisez une page web avec des animations CSS",
        imageURL: "https://images.pexels.com/photos/260922/pexels-photo-260922.jpeg?auto=compress&cs=tinysrgb&w=600",
        objectif: [
            "Mettre en œuvre des effets CSS graphiques avancés",
            "Assurer la cohérence graphique d'un site web",
            "Mettre en place son environnement Front-End",
            "Mettre en place une structure de navigation pour un site web",
            "Utiliser un système de gestion de versions pour le suivi du projet et son hébergement",
        ],
        gitHub: "https://github.com/crist51/p3_degorre_christophe",
        site: "",
        article:"",
    },
    {
        _id: 2,
        title: "La chouette agence",
        tag: ["formation", "frontend", "SEO"],
        desicription: "Optimisez un site web existant",
        imageURL: "https://rgalegria.github.io/lachouetteagencelyon/la-chouette-agence-lyon-social-banner.png",
        objectif: [
            "Réaliser une recherche des bonnes pratiques en développement web",
            "Optimiser la taille et la vitesse d’un site web",
            "Écrire un code HTML et CSS maintenable",
            " Optimiser le référencement d'un site web",
            " Assurer l'accessibilité d'un site web",
        ],
        article:"",
        site: "",
        gitHub: "https://github.com/crist51/P4_degorre_christophe",
    },
    {
        _id: 3,
        title: "Kanap",
        tag: ["formation", "frontend",],
        desicription: "Construisez un site e-commerce en JavaScript",
        imageURL: "https://www.mamaisonetnous.fr/wp-inside/uploads/2021/10/xscreenshot_20210527-143852_instagram-780x773.jpg.pagespeed.ic.ur2qSvxwVD.jpg",
        objectif: [
            "Interagir avec un web service avec JavaScript",
            "Valider des données issues de sources externes",
            "Créer un plan de test pour une application",
            "Gérer des événements JavaScript",
        ],
        gitHub: "https://github.com/crist51/P5_degorre_christophe",
        site: "",
        article:"",
    },
    {
        _id: 4,
        title: "Hot Takes",
        tag: ["formation", "backend",],
        desicription: "Construisez une API sécurisée pour une application d'avis d'épice épicée",
        imageURL: "https://st.depositphotos.com/1105977/2856/i/600/depositphotos_28566121-stock-photo-fire-ball.jpg",
        objectif: [
            "Stocker des données de manière sécurisée",
            "Implémenter un modèle logique de données conformément à la réglementation",
            "Mettre en œuvre des opérations CRUD de manière sécurisée",
        ],
        article:"",
        site: "",
        gitHub: "https://github.com/crist51/P6_degorre_christophe",
    },
    {
        _id: 5,
        title: "Groupomania",
        tag: ["formation", "frontend", "Backend", "freamwork", "backend"],
        desicription: "Créez un réseau social d’entreprise",
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQr6iEgGjGAEgs0escLrgTtSPVDurwLhzU6XA&usqp=CAU",
        objectif: [
            "Développer l’interface d’un site web grâce à un framework front-end",
            "Authentifier un utilisateur et maintenir sa session",
            "Implémenter un stockage de données sécurisé en utilisant une base de données",
        ],
        article:"",
        site: "",
        gitHub: "https://github.com/crist51/P7_degorre_christophe",
    },
    {
        _id: 6,
        title: "Quizz JavaSript",
        tag: ["perso", "frontend",],
        desicription: "Créez un quizz en JS",
        imageURL: "https://us.123rf.com/450wm/winterbee/winterbee1608/winterbee160800051/62797483-abstrait-d%C3%A9grad%C3%A9-orange-jaune-couleur-floue-fond-.jpg",
        objectif: [
            "Interagir avec un web service avec JavaScript",
            "Gérer des événements JavaScript",
        ],
        article:"Réalisationn d'un quiz Javascript avec des questions improbables serez-vous à la hauteur?",
        site: "https://crist51.github.io/quizzJavascript/",
        gitHub: "",
    },
    {
        _id: 7,
        title: "Aston Martin F1",
        tag: ["perso", "frontend", "animation"],
        desicription: "Créez un landing pages",
        imageURL: "https://www.f1news.fr/wp-content/uploads/2020/10/vettel-aston-martin-f1-2021.jpg",
        objectif: [
            "Assurer la cohérence graphique d'un site web",
            "Mettre en place son environnement Front-End",
            "Gérer des événements JavaScript",
        ],
        article:"Création d'une page animait d'une écurie de F1 un sport que j'apprécie particulièrement",
        site: "https://crist51.github.io/landing-page_01/",
        gitHub: "https://github.com/crist51/landing-page_01",
    },
    {
        _id: 8,
        title: "Astro Découverte",
        tag: ["perso", "frontend", "freamwork"],
        desicription: "Découverte du freamwork Astro, dans le but de comprendre son fonctionnement.",
        imageURL: "https://voonze.com/wp-content/uploads/2022/08/Web-framework-Astro-10-promises-faster-websites.jpg",
        objectif: [
            "Découvrir le freamwork ASTRO",
            "Comprendre ces avantages et ces inconvénients",
            "Manipulé et comprendre ASTRO",
        ],
        article: "Astro est un freamwork qui va nous permettre de créer des sites web en Javascript, il permet des creer des sites bassés essentiellement surdu HTML ce qui permet de gagner en performances. Il permet de greffer des comportements JS justes sur les éléments qui en on besoin. Il utilise une extension particulière ”. astro”.",
        gitHub: "https://github.com/crist51/christophe.degorre",
        site: "",
    },
    {
        _id: 9,
        title: "Optimisation du porftolio",
        tag: ["perso", "frontend", "SEO",],
        desicription: "Réalisé un site dynamique et facilement maintenable, sans backend.",
        imageURL: "https://images.pexels.com/photos/2517748/pexels-photo-2517748.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        objectif: [
            "Réaliser un site web Dynamique",
            "Optimiser la maintenabilité du site",
        ],
        article: "Mon portfolio était réalisé avec Astro, qui est orientée pour les sites statiques. Pour optimiser l'ajout de contenue, j'ai décidé de le rendre dynamique.<br> et optimiser le poid total du projet de 300ko je suis passé a 78ko grace à JS.",
        gitHub: "",
        site: "",
    },

]
