

export const projets = [
    {
        _id: 0,
        title: "Reservia",
        tag: ["formation", "frontend",],
        desicription: "Transformez une maquette en site web avec HTML & CSS",
        imageURL: "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        objectif: [
            "Implémenter une interface responsive",
            "Intégrer du contenu conformément à une maquette",
        ],
        gitHub: "https://github.com/crist51/P2_degorre_christophe",
        site: "",
        article:"https://github.com/crist51/P2_degorre_christophe",
    },
    {
        _id: 1,
        title: "Homyfood",
        tag: ["formation", "frontend", "animation"],
        desicription: "Dynamisez une page web avec des animations CSS",
        imageURL: "https://images.pexels.com/photos/260922/pexels-photo-260922.jpeg?auto=compress&cs=tinysrgb&w=600",
        objectif: [
            "Mettre en œuvre des effets CSS graphiques avancés",
            "Assurer la cohérence graphique d'un site web",
            "Mettre en place son environnement Front-End",
            "Mettre en place une structure de navigation pour un site web",
            "Utiliser un système de gestion de versions pour le suivi du projet et son hébergement",
        ],
        gitHub: "https://github.com/crist51/p3_degorre_christophe",
        site: "",
        article:"",
    },
    {
        _id: 2,
        title: "La chouette agence",
        tag: ["formation", "frontend", "SEO"],
        desicription: "Optimisez un site web existant",
        imageURL: "https://rgalegria.github.io/lachouetteagencelyon/la-chouette-agence-lyon-social-banner.png",
        objectif: [
            "Réaliser une recherche des bonnes pratiques en développement web",
            "Optimiser la taille et la vitesse d’un site web",
            "Écrire un code HTML et CSS maintenable",
            " Optimiser le référencement d'un site web",
            " Assurer l'accessibilité d'un site web",
        ],
        article:"",
        site: "",
        gitHub: "https://github.com/crist51/P4_degorre_christophe",
    },
    {
        _id: 3,
        title: "Kanap",
        tag: ["formation", "frontend",],
        desicription: "Construisez un site e-commerce en JavaScript",
        imageURL: "https://www.mamaisonetnous.fr/wp-inside/uploads/2021/10/xscreenshot_20210527-143852_instagram-780x773.jpg.pagespeed.ic.ur2qSvxwVD.jpg",
        objectif: [
            "Interagir avec un web service avec JavaScript",
            "Valider des données issues de sources externes",
            "Créer un plan de test pour une application",
            "Gérer des événements JavaScript",
        ],
        gitHub: "https://github.com/crist51/P5_degorre_christophe",
        site: "",
        article:"",
    },
    {
        _id: 4,
        title: "Hot Takes",
        tag: ["formation", "backend",],
        desicription: "Construisez une API sécurisée pour une application d'avis d'épice épicée",
        imageURL: "https://st.depositphotos.com/1105977/2856/i/600/depositphotos_28566121-stock-photo-fire-ball.jpg",
        objectif: [
            "Stocker des données de manière sécurisée",
            "Implémenter un modèle logique de données conformément à la réglementation",
            "Mettre en œuvre des opérations CRUD de manière sécurisée",
        ],
        article:"",
        site: "",
        gitHub: "https://github.com/crist51/P6_degorre_christophe",
    },
    {
        _id: 5,
        title: "Groupomania",
        tag: ["formation", "frontend", "Backend", "freamwork", "backend"],
        desicription: "Créez un réseau social d’entreprise",
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQr6iEgGjGAEgs0escLrgTtSPVDurwLhzU6XA&usqp=CAU",
        objectif: [
            "Développer l’interface d’un site web grâce à un framework front-end",
            "Authentifier un utilisateur et maintenir sa session",
            "Implémenter un stockage de données sécurisé en utilisant une base de données",
        ],
        article:"",
        site: "",
        gitHub: "https://github.com/crist51/P7_degorre_christophe",
    },
    {
        _id: 6,
        title: "Quizz JavaSript",
        tag: ["perso", "frontend",],
        desicription: "Créez un quizz en JS",
        imageURL: "https://us.123rf.com/450wm/winterbee/winterbee1608/winterbee160800051/62797483-abstrait-d%C3%A9grad%C3%A9-orange-jaune-couleur-floue-fond-.jpg",
        objectif: [
            "Interagir avec un web service avec JavaScript",
            "Gérer des événements JavaScript",
        ],
        article:"Réalisationn d'un quiz Javascript avec des questions improbables serez-vous à la hauteur?",
        site: "https://crist51.github.io/quizzJavascript/",
        gitHub: "",
    },
    {
        _id: 7,
        title: "Aston Martin F1",
        tag: ["perso", "frontend", "animation"],
        desicription: "Créez un landing pages",
        imageURL: "https://www.f1news.fr/wp-content/uploads/2020/10/vettel-aston-martin-f1-2021.jpg",
        objectif: [
            "Assurer la cohérence graphique d'un site web",
            "Mettre en place son environnement Front-End",
            "Gérer des événements JavaScript",
        ],
        article:"Création d'une page animait d'une écurie de F1 un sport que j'apprécie particulièrement",
        site: "https://crist51.github.io/landing-page_01/",
        gitHub: "https://github.com/crist51/landing-page_01",
    },
    {
        _id: 8,
        title: "Astro Découverte",
        tag: ["article", "frontend", "freamwork"],
        desicription: "Découverte du freamwork Astro, dans le but de comprendre son fonctionnement.",
        imageURL: "https://voonze.com/wp-content/uploads/2022/08/Web-framework-Astro-10-promises-faster-websites.jpg",
        objectif: [
            "Découvrir le freamwork ASTRO",
            "Comprendre ces avantages et ces inconvénients",
            "Manipulé et comprendre ASTRO",
        ],
        article: "Astro est un framework populaire pour les développeurs, offrant des outils pour accélérer le développement de logiciels. Les avantages incluent une productivité accrue grâce à des modèles de code prédéfinis et des bibliothèques de composants, ainsi qu'une conformité aux bonnes pratiques de développement. Cependant, l'apprentissage d'un nouveau framework peut être difficile et prendre du temps, en particulier pour les développeurs habitués à d'autres frameworks. De plus, la documentation d'Astro peut parfois être insuffisante ou désuète. Les développeurs doivent peser les avantages et les inconvénients d'Astro avant de décider s'il convient à leurs besoins de développement.",
        gitHub: "",
        site: "",
    },
    {
        _id: 9,
        title: "Optimisation du porftolio",
        tag: ["perso", "frontend", "SEO",],
        desicription: "Réalisé un site dynamique et facilement maintenable.",
        imageURL: "https://images.pexels.com/photos/2517748/pexels-photo-2517748.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        objectif: [
            "Réaliser un site web Dynamique",
            "Optimiser la maintenabilité du site",
        ],
        article: "Mon portfolio était réalisé avec Astro, qui est orientée pour les sites statiques. Pour optimiser l'ajout de contenue, j'ai décidé de le rendre dynamique.<br> et optimiser le poid total du projet de 300ko je suis passé a 78ko grace à JS.",
        gitHub: "",
        site: "",
    },
    {
        _id: 10,
        title: "Face à l'avancée de l'IA : ",
        tag: ["IA", "dev", "article"],
        desicription: "Le rôle des développeurs juniors de demain",
        imageURL: "https://www.larochellegc.com/wp-content/uploads/2020/06/Intelligence-artificielle-appliquee.-scaled-925x590-c-center.jpg",
        objectif: [
            "Reflexion IA",
            "Futur dans le metier",
        ],
        gitHub: "",
        site: "",
        article:"Avec l'avènement de l'intelligence artificielle et de la technologie de pointe en développement, les développeurs doivent constamment s'adapter aux nouveaux défis et aux opportunités qui se présentent. Les développeurs juniors, qui viennent tout juste d'entrer sur le marché du travail, sont confrontés à un avenir incertain alors que de plus en plus de tâches peuvent être automatisées.</br>Cependant, la technologie ne peut pas remplacer toutes les compétences humaines. Les développeurs juniors peuvent encore jouer un rôle important dans l'avenir en se concentrant sur les compétences que les IA ne peuvent pas remplacer, telles que la créativité, la résolution de problèmes complexes et la prise de décision stratégique. En développant ces compétences, les développeurs juniors peuvent continuer à être compétitifs sur le marché du travail, même face à l'avancée de l'IA.</br>En outre, les développeurs juniors peuvent également développer des compétences en intelligence artificielle, les utiliser pour créer de nouvelles solutions et les mettre en œuvre pour améliorer l'efficacité et la qualité du travail. Les développeurs juniors peuvent également s'engager dans la recherche pour améliorer les algorithmes d'IA et explorer les nouveaux horizons en matière de développement.</br></br>En conclusion, l'avenir des développeurs juniors dépend de leur capacité à évoluer avec les changements technologiques et à se concentrer sur les compétences qui sont uniques à l'être humain. En adoptant une attitude proactive et en continuant à se développer, les développeurs juniors peuvent continuer à avoir un impact significatif sur l'industrie du développement et sur l'avenir de la technologie en général.</br>Pour conclure, l'IA ne signifie pas la fin des développeurs juniors. Au lieu de cela, cela signifie qu'ils doivent s'adapter à de nouveaux défis et opportunités, en se concentrant sur les compétences qui les rendent uniques et en explorant les nouvelles avenues en matière de développement. Les développeurs juniors peuvent être l'avenir du développement en utilisant leurs compétences pour créer de nouvelles solutions et en explorant les nouveaux horizons en matière de développement."
    },

]


